version: "3.4"
services:
  storj.public.dappnode.eth:
    image: "storj.public.dappnode.eth:0.0.11"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.18.1
    restart: always
    ports:
      - "28967:28967"
    volumes:
      - "storj_identity:/app/identity"
      - "storj_storage:/app/config"
    environment:
      - AUTH_TOKEN
      - WALLET
      - STORAGE
      - EMAIL
volumes:
  storj_identity: {}
  storj_storage: {}
