version: "3.5"
services:
  storj.public.dappnode.eth:
    image: "storj.public.dappnode.eth:0.0.10"
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: v1.81.2
    restart: unless-stopped
    ports:
      - "28967:28967"
      - "28967:28967/udp"
    volumes:
      - "storj_identity:/root/.local/share/storj/identity/storagenode"
      - "storj_storage:/root/.local/share/storj/storagenode"
    environment:
      - AUTH_TOKEN
      - WALLET
      - STORAGE
      - EMAIL
      - EXTRA_OPTIONS
volumes:
  storj_identity: {}
  storj_storage: {}
